import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/lib/theme-provider";
import Header from "@/app/Header";
import "./globals.css";
import "react-big-calendar/lib/css/react-big-calendar.css";
import Script from "next/script";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Meru Test",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        fetchPriority: "low",
        rel: "icon",
        type: "imag/png",
        url: "/favicon.png?v=19",
      },
      // This will make animated favicon on
      {
        rel: "icon",
        type: "image/gif",
        url: "/favicon.gif?v=21",
        fetchPriority: "high",
      },
    ],
  },
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/*TODO: figure out why taikwind is not importing all classes*/}
        <Script
          src="https://cdn.tailwindcss.com"
          strategy="beforeInteractive"
        />
      </head>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
